#!/usr/bin/env perl

use 5.020;
use warnings;

use Getopt::Long;

sub main {
     my %options;

     GetOptions(\%options,
                'dir=s',
                'size=i',
     ) or die "You're using it wrong baka!";

     say $options{'dir'}, " ", $options{'size'};
}

&main if (__FILE__ eq $0);
